package net.greatsoft.main.db.helper;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import net.greatsoft.main.db.po.diabetes.DiabetesLedger;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DIABETES_LEDGER".
*/
public class DiabetesLedgerDao extends AbstractDao<DiabetesLedger, Void> {

    public static final String TABLENAME = "DIABETES_LEDGER";

    /**
     * Properties of entity DiabetesLedger.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property DiabetesLedgerId = new Property(0, String.class, "diabetesLedgerId", false, "DIABETES_LEDGER_ID");
        public final static Property PersonInfoId = new Property(1, String.class, "personInfoId", false, "PERSON_INFO_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property SexValue = new Property(3, String.class, "sexValue", false, "SEX_VALUE");
        public final static Property TelNo = new Property(4, String.class, "telNo", false, "TEL_NO");
        public final static Property NationalityValue = new Property(5, String.class, "nationalityValue", false, "NATIONALITY_VALUE");
        public final static Property OccupationValue = new Property(6, String.class, "occupationValue", false, "OCCUPATION_VALUE");
        public final static Property Household = new Property(7, String.class, "household", false, "HOUSEHOLD");
        public final static Property Age = new Property(8, Integer.class, "age", false, "AGE");
        public final static Property Address = new Property(9, String.class, "address", false, "ADDRESS");
        public final static Property Year = new Property(10, Integer.class, "year", false, "YEAR");
        public final static Property VisitCount = new Property(11, Integer.class, "visitCount", false, "VISIT_COUNT");
        public final static Property DiabetesManagLevelName = new Property(12, String.class, "diabetesManagLevelName", false, "DIABETES_MANAG_LEVEL_NAME");
        public final static Property DiabetesType = new Property(13, String.class, "diabetesType", false, "DIABETES_TYPE");
        public final static Property DiabetesFbg = new Property(14, Double.class, "diabetesFbg", false, "DIABETES_FBG");
        public final static Property CreateDate = new Property(15, java.util.Date.class, "createDate", false, "CREATE_DATE");
        public final static Property UnUseDrugs = new Property(16, String.class, "unUseDrugs", false, "UN_USE_DRUGS");
        public final static Property UseDrugs = new Property(17, String.class, "useDrugs", false, "USE_DRUGS");
        public final static Property FollowupDate1 = new Property(18, java.util.Date.class, "followupDate1", false, "FOLLOWUP_DATE1");
        public final static Property FollowupWay1 = new Property(19, String.class, "followupWay1", false, "FOLLOWUP_WAY1");
        public final static Property FollowupFbg1 = new Property(20, Double.class, "followupFbg1", false, "FOLLOWUP_FBG1");
        public final static Property FollowupOrgId1 = new Property(21, String.class, "followupOrgId1", false, "FOLLOWUP_ORG_ID1");
        public final static Property FollowupDate2 = new Property(22, java.util.Date.class, "followupDate2", false, "FOLLOWUP_DATE2");
        public final static Property FollowupWay2 = new Property(23, String.class, "followupWay2", false, "FOLLOWUP_WAY2");
        public final static Property FollowupFbg2 = new Property(24, Double.class, "followupFbg2", false, "FOLLOWUP_FBG2");
        public final static Property FollowupOrgId2 = new Property(25, String.class, "followupOrgId2", false, "FOLLOWUP_ORG_ID2");
        public final static Property FollowupDate3 = new Property(26, java.util.Date.class, "followupDate3", false, "FOLLOWUP_DATE3");
        public final static Property FollowupWay3 = new Property(27, String.class, "followupWay3", false, "FOLLOWUP_WAY3");
        public final static Property FollowupFbg3 = new Property(28, Double.class, "followupFbg3", false, "FOLLOWUP_FBG3");
        public final static Property FollowupOrgId3 = new Property(29, String.class, "followupOrgId3", false, "FOLLOWUP_ORG_ID3");
        public final static Property FollowupDate4 = new Property(30, java.util.Date.class, "followupDate4", false, "FOLLOWUP_DATE4");
        public final static Property FollowupWay4 = new Property(31, String.class, "followupWay4", false, "FOLLOWUP_WAY4");
        public final static Property FollowupFbg4 = new Property(32, Double.class, "followupFbg4", false, "FOLLOWUP_FBG4");
        public final static Property FollowupOrgId4 = new Property(33, String.class, "followupOrgId4", false, "FOLLOWUP_ORG_ID4");
        public final static Property FollowupDate5 = new Property(34, java.util.Date.class, "followupDate5", false, "FOLLOWUP_DATE5");
        public final static Property FollowupWay5 = new Property(35, String.class, "followupWay5", false, "FOLLOWUP_WAY5");
        public final static Property FollowupFbg5 = new Property(36, Double.class, "followupFbg5", false, "FOLLOWUP_FBG5");
        public final static Property FollowupOrgId5 = new Property(37, String.class, "followupOrgId5", false, "FOLLOWUP_ORG_ID5");
        public final static Property FollowupDate6 = new Property(38, java.util.Date.class, "followupDate6", false, "FOLLOWUP_DATE6");
        public final static Property FollowupWay6 = new Property(39, String.class, "followupWay6", false, "FOLLOWUP_WAY6");
        public final static Property FollowupFbg6 = new Property(40, Double.class, "followupFbg6", false, "FOLLOWUP_FBG6");
        public final static Property FollowupOrgId6 = new Property(41, String.class, "followupOrgId6", false, "FOLLOWUP_ORG_ID6");
        public final static Property FollowupDate7 = new Property(42, java.util.Date.class, "followupDate7", false, "FOLLOWUP_DATE7");
        public final static Property FollowupWay7 = new Property(43, String.class, "followupWay7", false, "FOLLOWUP_WAY7");
        public final static Property FollowupFbg7 = new Property(44, Double.class, "followupFbg7", false, "FOLLOWUP_FBG7");
        public final static Property FollowupOrgId7 = new Property(45, String.class, "followupOrgId7", false, "FOLLOWUP_ORG_ID7");
        public final static Property FollowupDate8 = new Property(46, java.util.Date.class, "followupDate8", false, "FOLLOWUP_DATE8");
        public final static Property FollowupWay8 = new Property(47, String.class, "followupWay8", false, "FOLLOWUP_WAY8");
        public final static Property FollowupFbg8 = new Property(48, Double.class, "followupFbg8", false, "FOLLOWUP_FBG8");
        public final static Property FollowupOrgId8 = new Property(49, String.class, "followupOrgId8", false, "FOLLOWUP_ORG_ID8");
        public final static Property FollowupDate9 = new Property(50, java.util.Date.class, "followupDate9", false, "FOLLOWUP_DATE9");
        public final static Property FollowupWay9 = new Property(51, String.class, "followupWay9", false, "FOLLOWUP_WAY9");
        public final static Property FollowupFbg9 = new Property(52, Double.class, "followupFbg9", false, "FOLLOWUP_FBG9");
        public final static Property FollowupOrgId9 = new Property(53, String.class, "followupOrgId9", false, "FOLLOWUP_ORG_ID9");
        public final static Property FollowupDate10 = new Property(54, java.util.Date.class, "followupDate10", false, "FOLLOWUP_DATE10");
        public final static Property FollowupWay10 = new Property(55, String.class, "followupWay10", false, "FOLLOWUP_WAY10");
        public final static Property FollowupFbg10 = new Property(56, Double.class, "followupFbg10", false, "FOLLOWUP_FBG10");
        public final static Property FollowupOrgId10 = new Property(57, String.class, "followupOrgId10", false, "FOLLOWUP_ORG_ID10");
        public final static Property FollowupDate11 = new Property(58, java.util.Date.class, "followupDate11", false, "FOLLOWUP_DATE11");
        public final static Property FollowupWay11 = new Property(59, String.class, "followupWay11", false, "FOLLOWUP_WAY11");
        public final static Property FollowupFbg11 = new Property(60, Double.class, "followupFbg11", false, "FOLLOWUP_FBG11");
        public final static Property FollowupOrgId11 = new Property(61, String.class, "followupOrgId11", false, "FOLLOWUP_ORG_ID11");
        public final static Property FollowupDate12 = new Property(62, java.util.Date.class, "followupDate12", false, "FOLLOWUP_DATE12");
        public final static Property FollowupWay12 = new Property(63, String.class, "followupWay12", false, "FOLLOWUP_WAY12");
        public final static Property FollowupFbg12 = new Property(64, Double.class, "followupFbg12", false, "FOLLOWUP_FBG12");
        public final static Property FollowupOrgId12 = new Property(65, String.class, "followupOrgId12", false, "FOLLOWUP_ORG_ID12");
        public final static Property FollowupDate13 = new Property(66, java.util.Date.class, "followupDate13", false, "FOLLOWUP_DATE13");
        public final static Property FollowupWay13 = new Property(67, String.class, "followupWay13", false, "FOLLOWUP_WAY13");
        public final static Property FollowupFbg13 = new Property(68, Double.class, "followupFbg13", false, "FOLLOWUP_FBG13");
        public final static Property FollowupOrgId13 = new Property(69, String.class, "followupOrgId13", false, "FOLLOWUP_ORG_ID13");
        public final static Property FollowupDate14 = new Property(70, java.util.Date.class, "followupDate14", false, "FOLLOWUP_DATE14");
        public final static Property FollowupWay14 = new Property(71, String.class, "followupWay14", false, "FOLLOWUP_WAY14");
        public final static Property FollowupFbg14 = new Property(72, Double.class, "followupFbg14", false, "FOLLOWUP_FBG14");
        public final static Property FollowupOrgId14 = new Property(73, String.class, "followupOrgId14", false, "FOLLOWUP_ORG_ID14");
        public final static Property FollowupDate15 = new Property(74, java.util.Date.class, "followupDate15", false, "FOLLOWUP_DATE15");
        public final static Property FollowupWay15 = new Property(75, String.class, "followupWay15", false, "FOLLOWUP_WAY15");
        public final static Property FollowupFbg15 = new Property(76, Double.class, "followupFbg15", false, "FOLLOWUP_FBG15");
        public final static Property FollowupOrgId15 = new Property(77, String.class, "followupOrgId15", false, "FOLLOWUP_ORG_ID15");
        public final static Property FollowupDate16 = new Property(78, java.util.Date.class, "followupDate16", false, "FOLLOWUP_DATE16");
        public final static Property FollowupWay16 = new Property(79, String.class, "followupWay16", false, "FOLLOWUP_WAY16");
        public final static Property FollowupFbg16 = new Property(80, Double.class, "followupFbg16", false, "FOLLOWUP_FBG16");
        public final static Property FollowupOrgId16 = new Property(81, String.class, "followupOrgId16", false, "FOLLOWUP_ORG_ID16");
        public final static Property FollowupDate17 = new Property(82, java.util.Date.class, "followupDate17", false, "FOLLOWUP_DATE17");
        public final static Property FollowupWay17 = new Property(83, String.class, "followupWay17", false, "FOLLOWUP_WAY17");
        public final static Property FollowupFbg17 = new Property(84, Double.class, "followupFbg17", false, "FOLLOWUP_FBG17");
        public final static Property FollowupOrgId17 = new Property(85, String.class, "followupOrgId17", false, "FOLLOWUP_ORG_ID17");
        public final static Property FollowupDate18 = new Property(86, java.util.Date.class, "followupDate18", false, "FOLLOWUP_DATE18");
        public final static Property FollowupWay18 = new Property(87, String.class, "followupWay18", false, "FOLLOWUP_WAY18");
        public final static Property FollowupFbg18 = new Property(88, Double.class, "followupFbg18", false, "FOLLOWUP_FBG18");
        public final static Property FollowupOrgId18 = new Property(89, String.class, "followupOrgId18", false, "FOLLOWUP_ORG_ID18");
        public final static Property FollowupDate19 = new Property(90, java.util.Date.class, "followupDate19", false, "FOLLOWUP_DATE19");
        public final static Property FollowupWay19 = new Property(91, String.class, "followupWay19", false, "FOLLOWUP_WAY19");
        public final static Property FollowupFbg19 = new Property(92, Double.class, "followupFbg19", false, "FOLLOWUP_FBG19");
        public final static Property FollowupOrgId19 = new Property(93, String.class, "followupOrgId19", false, "FOLLOWUP_ORG_ID19");
        public final static Property FollowupDate20 = new Property(94, java.util.Date.class, "followupDate20", false, "FOLLOWUP_DATE20");
        public final static Property FollowupWay20 = new Property(95, String.class, "followupWay20", false, "FOLLOWUP_WAY20");
        public final static Property FollowupFbg20 = new Property(96, Double.class, "followupFbg20", false, "FOLLOWUP_FBG20");
        public final static Property FollowupOrgId20 = new Property(97, String.class, "followupOrgId20", false, "FOLLOWUP_ORG_ID20");
        public final static Property IsStandard = new Property(98, String.class, "isStandard", false, "IS_STANDARD");
        public final static Property HealthExamDate = new Property(99, java.util.Date.class, "healthExamDate", false, "HEALTH_EXAM_DATE");
        public final static Property HealthExamEvaluate = new Property(100, String.class, "healthExamEvaluate", false, "HEALTH_EXAM_EVALUATE");
        public final static Property IsCancel = new Property(101, Integer.class, "isCancel", false, "IS_CANCEL");
    };


    public DiabetesLedgerDao(DaoConfig config) {
        super(config);
    }
    
    public DiabetesLedgerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DIABETES_LEDGER\" (" + //
                "\"DIABETES_LEDGER_ID\" TEXT," + // 0: diabetesLedgerId
                "\"PERSON_INFO_ID\" TEXT," + // 1: personInfoId
                "\"NAME\" TEXT," + // 2: name
                "\"SEX_VALUE\" TEXT," + // 3: sexValue
                "\"TEL_NO\" TEXT," + // 4: telNo
                "\"NATIONALITY_VALUE\" TEXT," + // 5: nationalityValue
                "\"OCCUPATION_VALUE\" TEXT," + // 6: occupationValue
                "\"HOUSEHOLD\" TEXT," + // 7: household
                "\"AGE\" INTEGER," + // 8: age
                "\"ADDRESS\" TEXT," + // 9: address
                "\"YEAR\" INTEGER," + // 10: year
                "\"VISIT_COUNT\" INTEGER," + // 11: visitCount
                "\"DIABETES_MANAG_LEVEL_NAME\" TEXT," + // 12: diabetesManagLevelName
                "\"DIABETES_TYPE\" TEXT," + // 13: diabetesType
                "\"DIABETES_FBG\" REAL," + // 14: diabetesFbg
                "\"CREATE_DATE\" INTEGER," + // 15: createDate
                "\"UN_USE_DRUGS\" TEXT," + // 16: unUseDrugs
                "\"USE_DRUGS\" TEXT," + // 17: useDrugs
                "\"FOLLOWUP_DATE1\" INTEGER," + // 18: followupDate1
                "\"FOLLOWUP_WAY1\" TEXT," + // 19: followupWay1
                "\"FOLLOWUP_FBG1\" REAL," + // 20: followupFbg1
                "\"FOLLOWUP_ORG_ID1\" TEXT," + // 21: followupOrgId1
                "\"FOLLOWUP_DATE2\" INTEGER," + // 22: followupDate2
                "\"FOLLOWUP_WAY2\" TEXT," + // 23: followupWay2
                "\"FOLLOWUP_FBG2\" REAL," + // 24: followupFbg2
                "\"FOLLOWUP_ORG_ID2\" TEXT," + // 25: followupOrgId2
                "\"FOLLOWUP_DATE3\" INTEGER," + // 26: followupDate3
                "\"FOLLOWUP_WAY3\" TEXT," + // 27: followupWay3
                "\"FOLLOWUP_FBG3\" REAL," + // 28: followupFbg3
                "\"FOLLOWUP_ORG_ID3\" TEXT," + // 29: followupOrgId3
                "\"FOLLOWUP_DATE4\" INTEGER," + // 30: followupDate4
                "\"FOLLOWUP_WAY4\" TEXT," + // 31: followupWay4
                "\"FOLLOWUP_FBG4\" REAL," + // 32: followupFbg4
                "\"FOLLOWUP_ORG_ID4\" TEXT," + // 33: followupOrgId4
                "\"FOLLOWUP_DATE5\" INTEGER," + // 34: followupDate5
                "\"FOLLOWUP_WAY5\" TEXT," + // 35: followupWay5
                "\"FOLLOWUP_FBG5\" REAL," + // 36: followupFbg5
                "\"FOLLOWUP_ORG_ID5\" TEXT," + // 37: followupOrgId5
                "\"FOLLOWUP_DATE6\" INTEGER," + // 38: followupDate6
                "\"FOLLOWUP_WAY6\" TEXT," + // 39: followupWay6
                "\"FOLLOWUP_FBG6\" REAL," + // 40: followupFbg6
                "\"FOLLOWUP_ORG_ID6\" TEXT," + // 41: followupOrgId6
                "\"FOLLOWUP_DATE7\" INTEGER," + // 42: followupDate7
                "\"FOLLOWUP_WAY7\" TEXT," + // 43: followupWay7
                "\"FOLLOWUP_FBG7\" REAL," + // 44: followupFbg7
                "\"FOLLOWUP_ORG_ID7\" TEXT," + // 45: followupOrgId7
                "\"FOLLOWUP_DATE8\" INTEGER," + // 46: followupDate8
                "\"FOLLOWUP_WAY8\" TEXT," + // 47: followupWay8
                "\"FOLLOWUP_FBG8\" REAL," + // 48: followupFbg8
                "\"FOLLOWUP_ORG_ID8\" TEXT," + // 49: followupOrgId8
                "\"FOLLOWUP_DATE9\" INTEGER," + // 50: followupDate9
                "\"FOLLOWUP_WAY9\" TEXT," + // 51: followupWay9
                "\"FOLLOWUP_FBG9\" REAL," + // 52: followupFbg9
                "\"FOLLOWUP_ORG_ID9\" TEXT," + // 53: followupOrgId9
                "\"FOLLOWUP_DATE10\" INTEGER," + // 54: followupDate10
                "\"FOLLOWUP_WAY10\" TEXT," + // 55: followupWay10
                "\"FOLLOWUP_FBG10\" REAL," + // 56: followupFbg10
                "\"FOLLOWUP_ORG_ID10\" TEXT," + // 57: followupOrgId10
                "\"FOLLOWUP_DATE11\" INTEGER," + // 58: followupDate11
                "\"FOLLOWUP_WAY11\" TEXT," + // 59: followupWay11
                "\"FOLLOWUP_FBG11\" REAL," + // 60: followupFbg11
                "\"FOLLOWUP_ORG_ID11\" TEXT," + // 61: followupOrgId11
                "\"FOLLOWUP_DATE12\" INTEGER," + // 62: followupDate12
                "\"FOLLOWUP_WAY12\" TEXT," + // 63: followupWay12
                "\"FOLLOWUP_FBG12\" REAL," + // 64: followupFbg12
                "\"FOLLOWUP_ORG_ID12\" TEXT," + // 65: followupOrgId12
                "\"FOLLOWUP_DATE13\" INTEGER," + // 66: followupDate13
                "\"FOLLOWUP_WAY13\" TEXT," + // 67: followupWay13
                "\"FOLLOWUP_FBG13\" REAL," + // 68: followupFbg13
                "\"FOLLOWUP_ORG_ID13\" TEXT," + // 69: followupOrgId13
                "\"FOLLOWUP_DATE14\" INTEGER," + // 70: followupDate14
                "\"FOLLOWUP_WAY14\" TEXT," + // 71: followupWay14
                "\"FOLLOWUP_FBG14\" REAL," + // 72: followupFbg14
                "\"FOLLOWUP_ORG_ID14\" TEXT," + // 73: followupOrgId14
                "\"FOLLOWUP_DATE15\" INTEGER," + // 74: followupDate15
                "\"FOLLOWUP_WAY15\" TEXT," + // 75: followupWay15
                "\"FOLLOWUP_FBG15\" REAL," + // 76: followupFbg15
                "\"FOLLOWUP_ORG_ID15\" TEXT," + // 77: followupOrgId15
                "\"FOLLOWUP_DATE16\" INTEGER," + // 78: followupDate16
                "\"FOLLOWUP_WAY16\" TEXT," + // 79: followupWay16
                "\"FOLLOWUP_FBG16\" REAL," + // 80: followupFbg16
                "\"FOLLOWUP_ORG_ID16\" TEXT," + // 81: followupOrgId16
                "\"FOLLOWUP_DATE17\" INTEGER," + // 82: followupDate17
                "\"FOLLOWUP_WAY17\" TEXT," + // 83: followupWay17
                "\"FOLLOWUP_FBG17\" REAL," + // 84: followupFbg17
                "\"FOLLOWUP_ORG_ID17\" TEXT," + // 85: followupOrgId17
                "\"FOLLOWUP_DATE18\" INTEGER," + // 86: followupDate18
                "\"FOLLOWUP_WAY18\" TEXT," + // 87: followupWay18
                "\"FOLLOWUP_FBG18\" REAL," + // 88: followupFbg18
                "\"FOLLOWUP_ORG_ID18\" TEXT," + // 89: followupOrgId18
                "\"FOLLOWUP_DATE19\" INTEGER," + // 90: followupDate19
                "\"FOLLOWUP_WAY19\" TEXT," + // 91: followupWay19
                "\"FOLLOWUP_FBG19\" REAL," + // 92: followupFbg19
                "\"FOLLOWUP_ORG_ID19\" TEXT," + // 93: followupOrgId19
                "\"FOLLOWUP_DATE20\" INTEGER," + // 94: followupDate20
                "\"FOLLOWUP_WAY20\" TEXT," + // 95: followupWay20
                "\"FOLLOWUP_FBG20\" REAL," + // 96: followupFbg20
                "\"FOLLOWUP_ORG_ID20\" TEXT," + // 97: followupOrgId20
                "\"IS_STANDARD\" TEXT," + // 98: isStandard
                "\"HEALTH_EXAM_DATE\" INTEGER," + // 99: healthExamDate
                "\"HEALTH_EXAM_EVALUATE\" TEXT," + // 100: healthExamEvaluate
                "\"IS_CANCEL\" INTEGER);"); // 101: isCancel
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DIABETES_LEDGER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DiabetesLedger entity) {
        stmt.clearBindings();
 
        String diabetesLedgerId = entity.getDiabetesLedgerId();
        if (diabetesLedgerId != null) {
            stmt.bindString(1, diabetesLedgerId);
        }
 
        String personInfoId = entity.getPersonInfoId();
        if (personInfoId != null) {
            stmt.bindString(2, personInfoId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String sexValue = entity.getSexValue();
        if (sexValue != null) {
            stmt.bindString(4, sexValue);
        }
 
        String telNo = entity.getTelNo();
        if (telNo != null) {
            stmt.bindString(5, telNo);
        }
 
        String nationalityValue = entity.getNationalityValue();
        if (nationalityValue != null) {
            stmt.bindString(6, nationalityValue);
        }
 
        String occupationValue = entity.getOccupationValue();
        if (occupationValue != null) {
            stmt.bindString(7, occupationValue);
        }
 
        String household = entity.getHousehold();
        if (household != null) {
            stmt.bindString(8, household);
        }
 
        Integer age = entity.getAge();
        if (age != null) {
            stmt.bindLong(9, age);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(10, address);
        }
 
        Integer year = entity.getYear();
        if (year != null) {
            stmt.bindLong(11, year);
        }
 
        Integer visitCount = entity.getVisitCount();
        if (visitCount != null) {
            stmt.bindLong(12, visitCount);
        }
 
        String diabetesManagLevelName = entity.getDiabetesManagLevelName();
        if (diabetesManagLevelName != null) {
            stmt.bindString(13, diabetesManagLevelName);
        }
 
        String diabetesType = entity.getDiabetesType();
        if (diabetesType != null) {
            stmt.bindString(14, diabetesType);
        }
 
        Double diabetesFbg = entity.getDiabetesFbg();
        if (diabetesFbg != null) {
            stmt.bindDouble(15, diabetesFbg);
        }
 
        java.util.Date createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindLong(16, createDate.getTime());
        }
 
        String unUseDrugs = entity.getUnUseDrugs();
        if (unUseDrugs != null) {
            stmt.bindString(17, unUseDrugs);
        }
 
        String useDrugs = entity.getUseDrugs();
        if (useDrugs != null) {
            stmt.bindString(18, useDrugs);
        }
 
        java.util.Date followupDate1 = entity.getFollowupDate1();
        if (followupDate1 != null) {
            stmt.bindLong(19, followupDate1.getTime());
        }
 
        String followupWay1 = entity.getFollowupWay1();
        if (followupWay1 != null) {
            stmt.bindString(20, followupWay1);
        }
 
        Double followupFbg1 = entity.getFollowupFbg1();
        if (followupFbg1 != null) {
            stmt.bindDouble(21, followupFbg1);
        }
 
        String followupOrgId1 = entity.getFollowupOrgId1();
        if (followupOrgId1 != null) {
            stmt.bindString(22, followupOrgId1);
        }
 
        java.util.Date followupDate2 = entity.getFollowupDate2();
        if (followupDate2 != null) {
            stmt.bindLong(23, followupDate2.getTime());
        }
 
        String followupWay2 = entity.getFollowupWay2();
        if (followupWay2 != null) {
            stmt.bindString(24, followupWay2);
        }
 
        Double followupFbg2 = entity.getFollowupFbg2();
        if (followupFbg2 != null) {
            stmt.bindDouble(25, followupFbg2);
        }
 
        String followupOrgId2 = entity.getFollowupOrgId2();
        if (followupOrgId2 != null) {
            stmt.bindString(26, followupOrgId2);
        }
 
        java.util.Date followupDate3 = entity.getFollowupDate3();
        if (followupDate3 != null) {
            stmt.bindLong(27, followupDate3.getTime());
        }
 
        String followupWay3 = entity.getFollowupWay3();
        if (followupWay3 != null) {
            stmt.bindString(28, followupWay3);
        }
 
        Double followupFbg3 = entity.getFollowupFbg3();
        if (followupFbg3 != null) {
            stmt.bindDouble(29, followupFbg3);
        }
 
        String followupOrgId3 = entity.getFollowupOrgId3();
        if (followupOrgId3 != null) {
            stmt.bindString(30, followupOrgId3);
        }
 
        java.util.Date followupDate4 = entity.getFollowupDate4();
        if (followupDate4 != null) {
            stmt.bindLong(31, followupDate4.getTime());
        }
 
        String followupWay4 = entity.getFollowupWay4();
        if (followupWay4 != null) {
            stmt.bindString(32, followupWay4);
        }
 
        Double followupFbg4 = entity.getFollowupFbg4();
        if (followupFbg4 != null) {
            stmt.bindDouble(33, followupFbg4);
        }
 
        String followupOrgId4 = entity.getFollowupOrgId4();
        if (followupOrgId4 != null) {
            stmt.bindString(34, followupOrgId4);
        }
 
        java.util.Date followupDate5 = entity.getFollowupDate5();
        if (followupDate5 != null) {
            stmt.bindLong(35, followupDate5.getTime());
        }
 
        String followupWay5 = entity.getFollowupWay5();
        if (followupWay5 != null) {
            stmt.bindString(36, followupWay5);
        }
 
        Double followupFbg5 = entity.getFollowupFbg5();
        if (followupFbg5 != null) {
            stmt.bindDouble(37, followupFbg5);
        }
 
        String followupOrgId5 = entity.getFollowupOrgId5();
        if (followupOrgId5 != null) {
            stmt.bindString(38, followupOrgId5);
        }
 
        java.util.Date followupDate6 = entity.getFollowupDate6();
        if (followupDate6 != null) {
            stmt.bindLong(39, followupDate6.getTime());
        }
 
        String followupWay6 = entity.getFollowupWay6();
        if (followupWay6 != null) {
            stmt.bindString(40, followupWay6);
        }
 
        Double followupFbg6 = entity.getFollowupFbg6();
        if (followupFbg6 != null) {
            stmt.bindDouble(41, followupFbg6);
        }
 
        String followupOrgId6 = entity.getFollowupOrgId6();
        if (followupOrgId6 != null) {
            stmt.bindString(42, followupOrgId6);
        }
 
        java.util.Date followupDate7 = entity.getFollowupDate7();
        if (followupDate7 != null) {
            stmt.bindLong(43, followupDate7.getTime());
        }
 
        String followupWay7 = entity.getFollowupWay7();
        if (followupWay7 != null) {
            stmt.bindString(44, followupWay7);
        }
 
        Double followupFbg7 = entity.getFollowupFbg7();
        if (followupFbg7 != null) {
            stmt.bindDouble(45, followupFbg7);
        }
 
        String followupOrgId7 = entity.getFollowupOrgId7();
        if (followupOrgId7 != null) {
            stmt.bindString(46, followupOrgId7);
        }
 
        java.util.Date followupDate8 = entity.getFollowupDate8();
        if (followupDate8 != null) {
            stmt.bindLong(47, followupDate8.getTime());
        }
 
        String followupWay8 = entity.getFollowupWay8();
        if (followupWay8 != null) {
            stmt.bindString(48, followupWay8);
        }
 
        Double followupFbg8 = entity.getFollowupFbg8();
        if (followupFbg8 != null) {
            stmt.bindDouble(49, followupFbg8);
        }
 
        String followupOrgId8 = entity.getFollowupOrgId8();
        if (followupOrgId8 != null) {
            stmt.bindString(50, followupOrgId8);
        }
 
        java.util.Date followupDate9 = entity.getFollowupDate9();
        if (followupDate9 != null) {
            stmt.bindLong(51, followupDate9.getTime());
        }
 
        String followupWay9 = entity.getFollowupWay9();
        if (followupWay9 != null) {
            stmt.bindString(52, followupWay9);
        }
 
        Double followupFbg9 = entity.getFollowupFbg9();
        if (followupFbg9 != null) {
            stmt.bindDouble(53, followupFbg9);
        }
 
        String followupOrgId9 = entity.getFollowupOrgId9();
        if (followupOrgId9 != null) {
            stmt.bindString(54, followupOrgId9);
        }
 
        java.util.Date followupDate10 = entity.getFollowupDate10();
        if (followupDate10 != null) {
            stmt.bindLong(55, followupDate10.getTime());
        }
 
        String followupWay10 = entity.getFollowupWay10();
        if (followupWay10 != null) {
            stmt.bindString(56, followupWay10);
        }
 
        Double followupFbg10 = entity.getFollowupFbg10();
        if (followupFbg10 != null) {
            stmt.bindDouble(57, followupFbg10);
        }
 
        String followupOrgId10 = entity.getFollowupOrgId10();
        if (followupOrgId10 != null) {
            stmt.bindString(58, followupOrgId10);
        }
 
        java.util.Date followupDate11 = entity.getFollowupDate11();
        if (followupDate11 != null) {
            stmt.bindLong(59, followupDate11.getTime());
        }
 
        String followupWay11 = entity.getFollowupWay11();
        if (followupWay11 != null) {
            stmt.bindString(60, followupWay11);
        }
 
        Double followupFbg11 = entity.getFollowupFbg11();
        if (followupFbg11 != null) {
            stmt.bindDouble(61, followupFbg11);
        }
 
        String followupOrgId11 = entity.getFollowupOrgId11();
        if (followupOrgId11 != null) {
            stmt.bindString(62, followupOrgId11);
        }
 
        java.util.Date followupDate12 = entity.getFollowupDate12();
        if (followupDate12 != null) {
            stmt.bindLong(63, followupDate12.getTime());
        }
 
        String followupWay12 = entity.getFollowupWay12();
        if (followupWay12 != null) {
            stmt.bindString(64, followupWay12);
        }
 
        Double followupFbg12 = entity.getFollowupFbg12();
        if (followupFbg12 != null) {
            stmt.bindDouble(65, followupFbg12);
        }
 
        String followupOrgId12 = entity.getFollowupOrgId12();
        if (followupOrgId12 != null) {
            stmt.bindString(66, followupOrgId12);
        }
 
        java.util.Date followupDate13 = entity.getFollowupDate13();
        if (followupDate13 != null) {
            stmt.bindLong(67, followupDate13.getTime());
        }
 
        String followupWay13 = entity.getFollowupWay13();
        if (followupWay13 != null) {
            stmt.bindString(68, followupWay13);
        }
 
        Double followupFbg13 = entity.getFollowupFbg13();
        if (followupFbg13 != null) {
            stmt.bindDouble(69, followupFbg13);
        }
 
        String followupOrgId13 = entity.getFollowupOrgId13();
        if (followupOrgId13 != null) {
            stmt.bindString(70, followupOrgId13);
        }
 
        java.util.Date followupDate14 = entity.getFollowupDate14();
        if (followupDate14 != null) {
            stmt.bindLong(71, followupDate14.getTime());
        }
 
        String followupWay14 = entity.getFollowupWay14();
        if (followupWay14 != null) {
            stmt.bindString(72, followupWay14);
        }
 
        Double followupFbg14 = entity.getFollowupFbg14();
        if (followupFbg14 != null) {
            stmt.bindDouble(73, followupFbg14);
        }
 
        String followupOrgId14 = entity.getFollowupOrgId14();
        if (followupOrgId14 != null) {
            stmt.bindString(74, followupOrgId14);
        }
 
        java.util.Date followupDate15 = entity.getFollowupDate15();
        if (followupDate15 != null) {
            stmt.bindLong(75, followupDate15.getTime());
        }
 
        String followupWay15 = entity.getFollowupWay15();
        if (followupWay15 != null) {
            stmt.bindString(76, followupWay15);
        }
 
        Double followupFbg15 = entity.getFollowupFbg15();
        if (followupFbg15 != null) {
            stmt.bindDouble(77, followupFbg15);
        }
 
        String followupOrgId15 = entity.getFollowupOrgId15();
        if (followupOrgId15 != null) {
            stmt.bindString(78, followupOrgId15);
        }
 
        java.util.Date followupDate16 = entity.getFollowupDate16();
        if (followupDate16 != null) {
            stmt.bindLong(79, followupDate16.getTime());
        }
 
        String followupWay16 = entity.getFollowupWay16();
        if (followupWay16 != null) {
            stmt.bindString(80, followupWay16);
        }
 
        Double followupFbg16 = entity.getFollowupFbg16();
        if (followupFbg16 != null) {
            stmt.bindDouble(81, followupFbg16);
        }
 
        String followupOrgId16 = entity.getFollowupOrgId16();
        if (followupOrgId16 != null) {
            stmt.bindString(82, followupOrgId16);
        }
 
        java.util.Date followupDate17 = entity.getFollowupDate17();
        if (followupDate17 != null) {
            stmt.bindLong(83, followupDate17.getTime());
        }
 
        String followupWay17 = entity.getFollowupWay17();
        if (followupWay17 != null) {
            stmt.bindString(84, followupWay17);
        }
 
        Double followupFbg17 = entity.getFollowupFbg17();
        if (followupFbg17 != null) {
            stmt.bindDouble(85, followupFbg17);
        }
 
        String followupOrgId17 = entity.getFollowupOrgId17();
        if (followupOrgId17 != null) {
            stmt.bindString(86, followupOrgId17);
        }
 
        java.util.Date followupDate18 = entity.getFollowupDate18();
        if (followupDate18 != null) {
            stmt.bindLong(87, followupDate18.getTime());
        }
 
        String followupWay18 = entity.getFollowupWay18();
        if (followupWay18 != null) {
            stmt.bindString(88, followupWay18);
        }
 
        Double followupFbg18 = entity.getFollowupFbg18();
        if (followupFbg18 != null) {
            stmt.bindDouble(89, followupFbg18);
        }
 
        String followupOrgId18 = entity.getFollowupOrgId18();
        if (followupOrgId18 != null) {
            stmt.bindString(90, followupOrgId18);
        }
 
        java.util.Date followupDate19 = entity.getFollowupDate19();
        if (followupDate19 != null) {
            stmt.bindLong(91, followupDate19.getTime());
        }
 
        String followupWay19 = entity.getFollowupWay19();
        if (followupWay19 != null) {
            stmt.bindString(92, followupWay19);
        }
 
        Double followupFbg19 = entity.getFollowupFbg19();
        if (followupFbg19 != null) {
            stmt.bindDouble(93, followupFbg19);
        }
 
        String followupOrgId19 = entity.getFollowupOrgId19();
        if (followupOrgId19 != null) {
            stmt.bindString(94, followupOrgId19);
        }
 
        java.util.Date followupDate20 = entity.getFollowupDate20();
        if (followupDate20 != null) {
            stmt.bindLong(95, followupDate20.getTime());
        }
 
        String followupWay20 = entity.getFollowupWay20();
        if (followupWay20 != null) {
            stmt.bindString(96, followupWay20);
        }
 
        Double followupFbg20 = entity.getFollowupFbg20();
        if (followupFbg20 != null) {
            stmt.bindDouble(97, followupFbg20);
        }
 
        String followupOrgId20 = entity.getFollowupOrgId20();
        if (followupOrgId20 != null) {
            stmt.bindString(98, followupOrgId20);
        }
 
        String isStandard = entity.getIsStandard();
        if (isStandard != null) {
            stmt.bindString(99, isStandard);
        }
 
        java.util.Date healthExamDate = entity.getHealthExamDate();
        if (healthExamDate != null) {
            stmt.bindLong(100, healthExamDate.getTime());
        }
 
        String healthExamEvaluate = entity.getHealthExamEvaluate();
        if (healthExamEvaluate != null) {
            stmt.bindString(101, healthExamEvaluate);
        }
 
        Integer isCancel = entity.getIsCancel();
        if (isCancel != null) {
            stmt.bindLong(102, isCancel);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DiabetesLedger entity) {
        stmt.clearBindings();
 
        String diabetesLedgerId = entity.getDiabetesLedgerId();
        if (diabetesLedgerId != null) {
            stmt.bindString(1, diabetesLedgerId);
        }
 
        String personInfoId = entity.getPersonInfoId();
        if (personInfoId != null) {
            stmt.bindString(2, personInfoId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String sexValue = entity.getSexValue();
        if (sexValue != null) {
            stmt.bindString(4, sexValue);
        }
 
        String telNo = entity.getTelNo();
        if (telNo != null) {
            stmt.bindString(5, telNo);
        }
 
        String nationalityValue = entity.getNationalityValue();
        if (nationalityValue != null) {
            stmt.bindString(6, nationalityValue);
        }
 
        String occupationValue = entity.getOccupationValue();
        if (occupationValue != null) {
            stmt.bindString(7, occupationValue);
        }
 
        String household = entity.getHousehold();
        if (household != null) {
            stmt.bindString(8, household);
        }
 
        Integer age = entity.getAge();
        if (age != null) {
            stmt.bindLong(9, age);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(10, address);
        }
 
        Integer year = entity.getYear();
        if (year != null) {
            stmt.bindLong(11, year);
        }
 
        Integer visitCount = entity.getVisitCount();
        if (visitCount != null) {
            stmt.bindLong(12, visitCount);
        }
 
        String diabetesManagLevelName = entity.getDiabetesManagLevelName();
        if (diabetesManagLevelName != null) {
            stmt.bindString(13, diabetesManagLevelName);
        }
 
        String diabetesType = entity.getDiabetesType();
        if (diabetesType != null) {
            stmt.bindString(14, diabetesType);
        }
 
        Double diabetesFbg = entity.getDiabetesFbg();
        if (diabetesFbg != null) {
            stmt.bindDouble(15, diabetesFbg);
        }
 
        java.util.Date createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindLong(16, createDate.getTime());
        }
 
        String unUseDrugs = entity.getUnUseDrugs();
        if (unUseDrugs != null) {
            stmt.bindString(17, unUseDrugs);
        }
 
        String useDrugs = entity.getUseDrugs();
        if (useDrugs != null) {
            stmt.bindString(18, useDrugs);
        }
 
        java.util.Date followupDate1 = entity.getFollowupDate1();
        if (followupDate1 != null) {
            stmt.bindLong(19, followupDate1.getTime());
        }
 
        String followupWay1 = entity.getFollowupWay1();
        if (followupWay1 != null) {
            stmt.bindString(20, followupWay1);
        }
 
        Double followupFbg1 = entity.getFollowupFbg1();
        if (followupFbg1 != null) {
            stmt.bindDouble(21, followupFbg1);
        }
 
        String followupOrgId1 = entity.getFollowupOrgId1();
        if (followupOrgId1 != null) {
            stmt.bindString(22, followupOrgId1);
        }
 
        java.util.Date followupDate2 = entity.getFollowupDate2();
        if (followupDate2 != null) {
            stmt.bindLong(23, followupDate2.getTime());
        }
 
        String followupWay2 = entity.getFollowupWay2();
        if (followupWay2 != null) {
            stmt.bindString(24, followupWay2);
        }
 
        Double followupFbg2 = entity.getFollowupFbg2();
        if (followupFbg2 != null) {
            stmt.bindDouble(25, followupFbg2);
        }
 
        String followupOrgId2 = entity.getFollowupOrgId2();
        if (followupOrgId2 != null) {
            stmt.bindString(26, followupOrgId2);
        }
 
        java.util.Date followupDate3 = entity.getFollowupDate3();
        if (followupDate3 != null) {
            stmt.bindLong(27, followupDate3.getTime());
        }
 
        String followupWay3 = entity.getFollowupWay3();
        if (followupWay3 != null) {
            stmt.bindString(28, followupWay3);
        }
 
        Double followupFbg3 = entity.getFollowupFbg3();
        if (followupFbg3 != null) {
            stmt.bindDouble(29, followupFbg3);
        }
 
        String followupOrgId3 = entity.getFollowupOrgId3();
        if (followupOrgId3 != null) {
            stmt.bindString(30, followupOrgId3);
        }
 
        java.util.Date followupDate4 = entity.getFollowupDate4();
        if (followupDate4 != null) {
            stmt.bindLong(31, followupDate4.getTime());
        }
 
        String followupWay4 = entity.getFollowupWay4();
        if (followupWay4 != null) {
            stmt.bindString(32, followupWay4);
        }
 
        Double followupFbg4 = entity.getFollowupFbg4();
        if (followupFbg4 != null) {
            stmt.bindDouble(33, followupFbg4);
        }
 
        String followupOrgId4 = entity.getFollowupOrgId4();
        if (followupOrgId4 != null) {
            stmt.bindString(34, followupOrgId4);
        }
 
        java.util.Date followupDate5 = entity.getFollowupDate5();
        if (followupDate5 != null) {
            stmt.bindLong(35, followupDate5.getTime());
        }
 
        String followupWay5 = entity.getFollowupWay5();
        if (followupWay5 != null) {
            stmt.bindString(36, followupWay5);
        }
 
        Double followupFbg5 = entity.getFollowupFbg5();
        if (followupFbg5 != null) {
            stmt.bindDouble(37, followupFbg5);
        }
 
        String followupOrgId5 = entity.getFollowupOrgId5();
        if (followupOrgId5 != null) {
            stmt.bindString(38, followupOrgId5);
        }
 
        java.util.Date followupDate6 = entity.getFollowupDate6();
        if (followupDate6 != null) {
            stmt.bindLong(39, followupDate6.getTime());
        }
 
        String followupWay6 = entity.getFollowupWay6();
        if (followupWay6 != null) {
            stmt.bindString(40, followupWay6);
        }
 
        Double followupFbg6 = entity.getFollowupFbg6();
        if (followupFbg6 != null) {
            stmt.bindDouble(41, followupFbg6);
        }
 
        String followupOrgId6 = entity.getFollowupOrgId6();
        if (followupOrgId6 != null) {
            stmt.bindString(42, followupOrgId6);
        }
 
        java.util.Date followupDate7 = entity.getFollowupDate7();
        if (followupDate7 != null) {
            stmt.bindLong(43, followupDate7.getTime());
        }
 
        String followupWay7 = entity.getFollowupWay7();
        if (followupWay7 != null) {
            stmt.bindString(44, followupWay7);
        }
 
        Double followupFbg7 = entity.getFollowupFbg7();
        if (followupFbg7 != null) {
            stmt.bindDouble(45, followupFbg7);
        }
 
        String followupOrgId7 = entity.getFollowupOrgId7();
        if (followupOrgId7 != null) {
            stmt.bindString(46, followupOrgId7);
        }
 
        java.util.Date followupDate8 = entity.getFollowupDate8();
        if (followupDate8 != null) {
            stmt.bindLong(47, followupDate8.getTime());
        }
 
        String followupWay8 = entity.getFollowupWay8();
        if (followupWay8 != null) {
            stmt.bindString(48, followupWay8);
        }
 
        Double followupFbg8 = entity.getFollowupFbg8();
        if (followupFbg8 != null) {
            stmt.bindDouble(49, followupFbg8);
        }
 
        String followupOrgId8 = entity.getFollowupOrgId8();
        if (followupOrgId8 != null) {
            stmt.bindString(50, followupOrgId8);
        }
 
        java.util.Date followupDate9 = entity.getFollowupDate9();
        if (followupDate9 != null) {
            stmt.bindLong(51, followupDate9.getTime());
        }
 
        String followupWay9 = entity.getFollowupWay9();
        if (followupWay9 != null) {
            stmt.bindString(52, followupWay9);
        }
 
        Double followupFbg9 = entity.getFollowupFbg9();
        if (followupFbg9 != null) {
            stmt.bindDouble(53, followupFbg9);
        }
 
        String followupOrgId9 = entity.getFollowupOrgId9();
        if (followupOrgId9 != null) {
            stmt.bindString(54, followupOrgId9);
        }
 
        java.util.Date followupDate10 = entity.getFollowupDate10();
        if (followupDate10 != null) {
            stmt.bindLong(55, followupDate10.getTime());
        }
 
        String followupWay10 = entity.getFollowupWay10();
        if (followupWay10 != null) {
            stmt.bindString(56, followupWay10);
        }
 
        Double followupFbg10 = entity.getFollowupFbg10();
        if (followupFbg10 != null) {
            stmt.bindDouble(57, followupFbg10);
        }
 
        String followupOrgId10 = entity.getFollowupOrgId10();
        if (followupOrgId10 != null) {
            stmt.bindString(58, followupOrgId10);
        }
 
        java.util.Date followupDate11 = entity.getFollowupDate11();
        if (followupDate11 != null) {
            stmt.bindLong(59, followupDate11.getTime());
        }
 
        String followupWay11 = entity.getFollowupWay11();
        if (followupWay11 != null) {
            stmt.bindString(60, followupWay11);
        }
 
        Double followupFbg11 = entity.getFollowupFbg11();
        if (followupFbg11 != null) {
            stmt.bindDouble(61, followupFbg11);
        }
 
        String followupOrgId11 = entity.getFollowupOrgId11();
        if (followupOrgId11 != null) {
            stmt.bindString(62, followupOrgId11);
        }
 
        java.util.Date followupDate12 = entity.getFollowupDate12();
        if (followupDate12 != null) {
            stmt.bindLong(63, followupDate12.getTime());
        }
 
        String followupWay12 = entity.getFollowupWay12();
        if (followupWay12 != null) {
            stmt.bindString(64, followupWay12);
        }
 
        Double followupFbg12 = entity.getFollowupFbg12();
        if (followupFbg12 != null) {
            stmt.bindDouble(65, followupFbg12);
        }
 
        String followupOrgId12 = entity.getFollowupOrgId12();
        if (followupOrgId12 != null) {
            stmt.bindString(66, followupOrgId12);
        }
 
        java.util.Date followupDate13 = entity.getFollowupDate13();
        if (followupDate13 != null) {
            stmt.bindLong(67, followupDate13.getTime());
        }
 
        String followupWay13 = entity.getFollowupWay13();
        if (followupWay13 != null) {
            stmt.bindString(68, followupWay13);
        }
 
        Double followupFbg13 = entity.getFollowupFbg13();
        if (followupFbg13 != null) {
            stmt.bindDouble(69, followupFbg13);
        }
 
        String followupOrgId13 = entity.getFollowupOrgId13();
        if (followupOrgId13 != null) {
            stmt.bindString(70, followupOrgId13);
        }
 
        java.util.Date followupDate14 = entity.getFollowupDate14();
        if (followupDate14 != null) {
            stmt.bindLong(71, followupDate14.getTime());
        }
 
        String followupWay14 = entity.getFollowupWay14();
        if (followupWay14 != null) {
            stmt.bindString(72, followupWay14);
        }
 
        Double followupFbg14 = entity.getFollowupFbg14();
        if (followupFbg14 != null) {
            stmt.bindDouble(73, followupFbg14);
        }
 
        String followupOrgId14 = entity.getFollowupOrgId14();
        if (followupOrgId14 != null) {
            stmt.bindString(74, followupOrgId14);
        }
 
        java.util.Date followupDate15 = entity.getFollowupDate15();
        if (followupDate15 != null) {
            stmt.bindLong(75, followupDate15.getTime());
        }
 
        String followupWay15 = entity.getFollowupWay15();
        if (followupWay15 != null) {
            stmt.bindString(76, followupWay15);
        }
 
        Double followupFbg15 = entity.getFollowupFbg15();
        if (followupFbg15 != null) {
            stmt.bindDouble(77, followupFbg15);
        }
 
        String followupOrgId15 = entity.getFollowupOrgId15();
        if (followupOrgId15 != null) {
            stmt.bindString(78, followupOrgId15);
        }
 
        java.util.Date followupDate16 = entity.getFollowupDate16();
        if (followupDate16 != null) {
            stmt.bindLong(79, followupDate16.getTime());
        }
 
        String followupWay16 = entity.getFollowupWay16();
        if (followupWay16 != null) {
            stmt.bindString(80, followupWay16);
        }
 
        Double followupFbg16 = entity.getFollowupFbg16();
        if (followupFbg16 != null) {
            stmt.bindDouble(81, followupFbg16);
        }
 
        String followupOrgId16 = entity.getFollowupOrgId16();
        if (followupOrgId16 != null) {
            stmt.bindString(82, followupOrgId16);
        }
 
        java.util.Date followupDate17 = entity.getFollowupDate17();
        if (followupDate17 != null) {
            stmt.bindLong(83, followupDate17.getTime());
        }
 
        String followupWay17 = entity.getFollowupWay17();
        if (followupWay17 != null) {
            stmt.bindString(84, followupWay17);
        }
 
        Double followupFbg17 = entity.getFollowupFbg17();
        if (followupFbg17 != null) {
            stmt.bindDouble(85, followupFbg17);
        }
 
        String followupOrgId17 = entity.getFollowupOrgId17();
        if (followupOrgId17 != null) {
            stmt.bindString(86, followupOrgId17);
        }
 
        java.util.Date followupDate18 = entity.getFollowupDate18();
        if (followupDate18 != null) {
            stmt.bindLong(87, followupDate18.getTime());
        }
 
        String followupWay18 = entity.getFollowupWay18();
        if (followupWay18 != null) {
            stmt.bindString(88, followupWay18);
        }
 
        Double followupFbg18 = entity.getFollowupFbg18();
        if (followupFbg18 != null) {
            stmt.bindDouble(89, followupFbg18);
        }
 
        String followupOrgId18 = entity.getFollowupOrgId18();
        if (followupOrgId18 != null) {
            stmt.bindString(90, followupOrgId18);
        }
 
        java.util.Date followupDate19 = entity.getFollowupDate19();
        if (followupDate19 != null) {
            stmt.bindLong(91, followupDate19.getTime());
        }
 
        String followupWay19 = entity.getFollowupWay19();
        if (followupWay19 != null) {
            stmt.bindString(92, followupWay19);
        }
 
        Double followupFbg19 = entity.getFollowupFbg19();
        if (followupFbg19 != null) {
            stmt.bindDouble(93, followupFbg19);
        }
 
        String followupOrgId19 = entity.getFollowupOrgId19();
        if (followupOrgId19 != null) {
            stmt.bindString(94, followupOrgId19);
        }
 
        java.util.Date followupDate20 = entity.getFollowupDate20();
        if (followupDate20 != null) {
            stmt.bindLong(95, followupDate20.getTime());
        }
 
        String followupWay20 = entity.getFollowupWay20();
        if (followupWay20 != null) {
            stmt.bindString(96, followupWay20);
        }
 
        Double followupFbg20 = entity.getFollowupFbg20();
        if (followupFbg20 != null) {
            stmt.bindDouble(97, followupFbg20);
        }
 
        String followupOrgId20 = entity.getFollowupOrgId20();
        if (followupOrgId20 != null) {
            stmt.bindString(98, followupOrgId20);
        }
 
        String isStandard = entity.getIsStandard();
        if (isStandard != null) {
            stmt.bindString(99, isStandard);
        }
 
        java.util.Date healthExamDate = entity.getHealthExamDate();
        if (healthExamDate != null) {
            stmt.bindLong(100, healthExamDate.getTime());
        }
 
        String healthExamEvaluate = entity.getHealthExamEvaluate();
        if (healthExamEvaluate != null) {
            stmt.bindString(101, healthExamEvaluate);
        }
 
        Integer isCancel = entity.getIsCancel();
        if (isCancel != null) {
            stmt.bindLong(102, isCancel);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public DiabetesLedger readEntity(Cursor cursor, int offset) {
        DiabetesLedger entity = new DiabetesLedger( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // diabetesLedgerId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // personInfoId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // sexValue
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // telNo
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // nationalityValue
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // occupationValue
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // household
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // age
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // address
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // year
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11), // visitCount
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // diabetesManagLevelName
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // diabetesType
            cursor.isNull(offset + 14) ? null : cursor.getDouble(offset + 14), // diabetesFbg
            cursor.isNull(offset + 15) ? null : new java.util.Date(cursor.getLong(offset + 15)), // createDate
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // unUseDrugs
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // useDrugs
            cursor.isNull(offset + 18) ? null : new java.util.Date(cursor.getLong(offset + 18)), // followupDate1
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // followupWay1
            cursor.isNull(offset + 20) ? null : cursor.getDouble(offset + 20), // followupFbg1
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // followupOrgId1
            cursor.isNull(offset + 22) ? null : new java.util.Date(cursor.getLong(offset + 22)), // followupDate2
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // followupWay2
            cursor.isNull(offset + 24) ? null : cursor.getDouble(offset + 24), // followupFbg2
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // followupOrgId2
            cursor.isNull(offset + 26) ? null : new java.util.Date(cursor.getLong(offset + 26)), // followupDate3
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // followupWay3
            cursor.isNull(offset + 28) ? null : cursor.getDouble(offset + 28), // followupFbg3
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // followupOrgId3
            cursor.isNull(offset + 30) ? null : new java.util.Date(cursor.getLong(offset + 30)), // followupDate4
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // followupWay4
            cursor.isNull(offset + 32) ? null : cursor.getDouble(offset + 32), // followupFbg4
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // followupOrgId4
            cursor.isNull(offset + 34) ? null : new java.util.Date(cursor.getLong(offset + 34)), // followupDate5
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // followupWay5
            cursor.isNull(offset + 36) ? null : cursor.getDouble(offset + 36), // followupFbg5
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // followupOrgId5
            cursor.isNull(offset + 38) ? null : new java.util.Date(cursor.getLong(offset + 38)), // followupDate6
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // followupWay6
            cursor.isNull(offset + 40) ? null : cursor.getDouble(offset + 40), // followupFbg6
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41), // followupOrgId6
            cursor.isNull(offset + 42) ? null : new java.util.Date(cursor.getLong(offset + 42)), // followupDate7
            cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43), // followupWay7
            cursor.isNull(offset + 44) ? null : cursor.getDouble(offset + 44), // followupFbg7
            cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45), // followupOrgId7
            cursor.isNull(offset + 46) ? null : new java.util.Date(cursor.getLong(offset + 46)), // followupDate8
            cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47), // followupWay8
            cursor.isNull(offset + 48) ? null : cursor.getDouble(offset + 48), // followupFbg8
            cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49), // followupOrgId8
            cursor.isNull(offset + 50) ? null : new java.util.Date(cursor.getLong(offset + 50)), // followupDate9
            cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51), // followupWay9
            cursor.isNull(offset + 52) ? null : cursor.getDouble(offset + 52), // followupFbg9
            cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53), // followupOrgId9
            cursor.isNull(offset + 54) ? null : new java.util.Date(cursor.getLong(offset + 54)), // followupDate10
            cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55), // followupWay10
            cursor.isNull(offset + 56) ? null : cursor.getDouble(offset + 56), // followupFbg10
            cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57), // followupOrgId10
            cursor.isNull(offset + 58) ? null : new java.util.Date(cursor.getLong(offset + 58)), // followupDate11
            cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59), // followupWay11
            cursor.isNull(offset + 60) ? null : cursor.getDouble(offset + 60), // followupFbg11
            cursor.isNull(offset + 61) ? null : cursor.getString(offset + 61), // followupOrgId11
            cursor.isNull(offset + 62) ? null : new java.util.Date(cursor.getLong(offset + 62)), // followupDate12
            cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63), // followupWay12
            cursor.isNull(offset + 64) ? null : cursor.getDouble(offset + 64), // followupFbg12
            cursor.isNull(offset + 65) ? null : cursor.getString(offset + 65), // followupOrgId12
            cursor.isNull(offset + 66) ? null : new java.util.Date(cursor.getLong(offset + 66)), // followupDate13
            cursor.isNull(offset + 67) ? null : cursor.getString(offset + 67), // followupWay13
            cursor.isNull(offset + 68) ? null : cursor.getDouble(offset + 68), // followupFbg13
            cursor.isNull(offset + 69) ? null : cursor.getString(offset + 69), // followupOrgId13
            cursor.isNull(offset + 70) ? null : new java.util.Date(cursor.getLong(offset + 70)), // followupDate14
            cursor.isNull(offset + 71) ? null : cursor.getString(offset + 71), // followupWay14
            cursor.isNull(offset + 72) ? null : cursor.getDouble(offset + 72), // followupFbg14
            cursor.isNull(offset + 73) ? null : cursor.getString(offset + 73), // followupOrgId14
            cursor.isNull(offset + 74) ? null : new java.util.Date(cursor.getLong(offset + 74)), // followupDate15
            cursor.isNull(offset + 75) ? null : cursor.getString(offset + 75), // followupWay15
            cursor.isNull(offset + 76) ? null : cursor.getDouble(offset + 76), // followupFbg15
            cursor.isNull(offset + 77) ? null : cursor.getString(offset + 77), // followupOrgId15
            cursor.isNull(offset + 78) ? null : new java.util.Date(cursor.getLong(offset + 78)), // followupDate16
            cursor.isNull(offset + 79) ? null : cursor.getString(offset + 79), // followupWay16
            cursor.isNull(offset + 80) ? null : cursor.getDouble(offset + 80), // followupFbg16
            cursor.isNull(offset + 81) ? null : cursor.getString(offset + 81), // followupOrgId16
            cursor.isNull(offset + 82) ? null : new java.util.Date(cursor.getLong(offset + 82)), // followupDate17
            cursor.isNull(offset + 83) ? null : cursor.getString(offset + 83), // followupWay17
            cursor.isNull(offset + 84) ? null : cursor.getDouble(offset + 84), // followupFbg17
            cursor.isNull(offset + 85) ? null : cursor.getString(offset + 85), // followupOrgId17
            cursor.isNull(offset + 86) ? null : new java.util.Date(cursor.getLong(offset + 86)), // followupDate18
            cursor.isNull(offset + 87) ? null : cursor.getString(offset + 87), // followupWay18
            cursor.isNull(offset + 88) ? null : cursor.getDouble(offset + 88), // followupFbg18
            cursor.isNull(offset + 89) ? null : cursor.getString(offset + 89), // followupOrgId18
            cursor.isNull(offset + 90) ? null : new java.util.Date(cursor.getLong(offset + 90)), // followupDate19
            cursor.isNull(offset + 91) ? null : cursor.getString(offset + 91), // followupWay19
            cursor.isNull(offset + 92) ? null : cursor.getDouble(offset + 92), // followupFbg19
            cursor.isNull(offset + 93) ? null : cursor.getString(offset + 93), // followupOrgId19
            cursor.isNull(offset + 94) ? null : new java.util.Date(cursor.getLong(offset + 94)), // followupDate20
            cursor.isNull(offset + 95) ? null : cursor.getString(offset + 95), // followupWay20
            cursor.isNull(offset + 96) ? null : cursor.getDouble(offset + 96), // followupFbg20
            cursor.isNull(offset + 97) ? null : cursor.getString(offset + 97), // followupOrgId20
            cursor.isNull(offset + 98) ? null : cursor.getString(offset + 98), // isStandard
            cursor.isNull(offset + 99) ? null : new java.util.Date(cursor.getLong(offset + 99)), // healthExamDate
            cursor.isNull(offset + 100) ? null : cursor.getString(offset + 100), // healthExamEvaluate
            cursor.isNull(offset + 101) ? null : cursor.getInt(offset + 101) // isCancel
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DiabetesLedger entity, int offset) {
        entity.setDiabetesLedgerId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setPersonInfoId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSexValue(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTelNo(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setNationalityValue(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setOccupationValue(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setHousehold(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setAge(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setAddress(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setYear(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setVisitCount(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
        entity.setDiabetesManagLevelName(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setDiabetesType(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setDiabetesFbg(cursor.isNull(offset + 14) ? null : cursor.getDouble(offset + 14));
        entity.setCreateDate(cursor.isNull(offset + 15) ? null : new java.util.Date(cursor.getLong(offset + 15)));
        entity.setUnUseDrugs(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setUseDrugs(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setFollowupDate1(cursor.isNull(offset + 18) ? null : new java.util.Date(cursor.getLong(offset + 18)));
        entity.setFollowupWay1(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setFollowupFbg1(cursor.isNull(offset + 20) ? null : cursor.getDouble(offset + 20));
        entity.setFollowupOrgId1(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setFollowupDate2(cursor.isNull(offset + 22) ? null : new java.util.Date(cursor.getLong(offset + 22)));
        entity.setFollowupWay2(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setFollowupFbg2(cursor.isNull(offset + 24) ? null : cursor.getDouble(offset + 24));
        entity.setFollowupOrgId2(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setFollowupDate3(cursor.isNull(offset + 26) ? null : new java.util.Date(cursor.getLong(offset + 26)));
        entity.setFollowupWay3(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setFollowupFbg3(cursor.isNull(offset + 28) ? null : cursor.getDouble(offset + 28));
        entity.setFollowupOrgId3(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setFollowupDate4(cursor.isNull(offset + 30) ? null : new java.util.Date(cursor.getLong(offset + 30)));
        entity.setFollowupWay4(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setFollowupFbg4(cursor.isNull(offset + 32) ? null : cursor.getDouble(offset + 32));
        entity.setFollowupOrgId4(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setFollowupDate5(cursor.isNull(offset + 34) ? null : new java.util.Date(cursor.getLong(offset + 34)));
        entity.setFollowupWay5(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setFollowupFbg5(cursor.isNull(offset + 36) ? null : cursor.getDouble(offset + 36));
        entity.setFollowupOrgId5(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setFollowupDate6(cursor.isNull(offset + 38) ? null : new java.util.Date(cursor.getLong(offset + 38)));
        entity.setFollowupWay6(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setFollowupFbg6(cursor.isNull(offset + 40) ? null : cursor.getDouble(offset + 40));
        entity.setFollowupOrgId6(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
        entity.setFollowupDate7(cursor.isNull(offset + 42) ? null : new java.util.Date(cursor.getLong(offset + 42)));
        entity.setFollowupWay7(cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43));
        entity.setFollowupFbg7(cursor.isNull(offset + 44) ? null : cursor.getDouble(offset + 44));
        entity.setFollowupOrgId7(cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45));
        entity.setFollowupDate8(cursor.isNull(offset + 46) ? null : new java.util.Date(cursor.getLong(offset + 46)));
        entity.setFollowupWay8(cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47));
        entity.setFollowupFbg8(cursor.isNull(offset + 48) ? null : cursor.getDouble(offset + 48));
        entity.setFollowupOrgId8(cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49));
        entity.setFollowupDate9(cursor.isNull(offset + 50) ? null : new java.util.Date(cursor.getLong(offset + 50)));
        entity.setFollowupWay9(cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51));
        entity.setFollowupFbg9(cursor.isNull(offset + 52) ? null : cursor.getDouble(offset + 52));
        entity.setFollowupOrgId9(cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53));
        entity.setFollowupDate10(cursor.isNull(offset + 54) ? null : new java.util.Date(cursor.getLong(offset + 54)));
        entity.setFollowupWay10(cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55));
        entity.setFollowupFbg10(cursor.isNull(offset + 56) ? null : cursor.getDouble(offset + 56));
        entity.setFollowupOrgId10(cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57));
        entity.setFollowupDate11(cursor.isNull(offset + 58) ? null : new java.util.Date(cursor.getLong(offset + 58)));
        entity.setFollowupWay11(cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59));
        entity.setFollowupFbg11(cursor.isNull(offset + 60) ? null : cursor.getDouble(offset + 60));
        entity.setFollowupOrgId11(cursor.isNull(offset + 61) ? null : cursor.getString(offset + 61));
        entity.setFollowupDate12(cursor.isNull(offset + 62) ? null : new java.util.Date(cursor.getLong(offset + 62)));
        entity.setFollowupWay12(cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63));
        entity.setFollowupFbg12(cursor.isNull(offset + 64) ? null : cursor.getDouble(offset + 64));
        entity.setFollowupOrgId12(cursor.isNull(offset + 65) ? null : cursor.getString(offset + 65));
        entity.setFollowupDate13(cursor.isNull(offset + 66) ? null : new java.util.Date(cursor.getLong(offset + 66)));
        entity.setFollowupWay13(cursor.isNull(offset + 67) ? null : cursor.getString(offset + 67));
        entity.setFollowupFbg13(cursor.isNull(offset + 68) ? null : cursor.getDouble(offset + 68));
        entity.setFollowupOrgId13(cursor.isNull(offset + 69) ? null : cursor.getString(offset + 69));
        entity.setFollowupDate14(cursor.isNull(offset + 70) ? null : new java.util.Date(cursor.getLong(offset + 70)));
        entity.setFollowupWay14(cursor.isNull(offset + 71) ? null : cursor.getString(offset + 71));
        entity.setFollowupFbg14(cursor.isNull(offset + 72) ? null : cursor.getDouble(offset + 72));
        entity.setFollowupOrgId14(cursor.isNull(offset + 73) ? null : cursor.getString(offset + 73));
        entity.setFollowupDate15(cursor.isNull(offset + 74) ? null : new java.util.Date(cursor.getLong(offset + 74)));
        entity.setFollowupWay15(cursor.isNull(offset + 75) ? null : cursor.getString(offset + 75));
        entity.setFollowupFbg15(cursor.isNull(offset + 76) ? null : cursor.getDouble(offset + 76));
        entity.setFollowupOrgId15(cursor.isNull(offset + 77) ? null : cursor.getString(offset + 77));
        entity.setFollowupDate16(cursor.isNull(offset + 78) ? null : new java.util.Date(cursor.getLong(offset + 78)));
        entity.setFollowupWay16(cursor.isNull(offset + 79) ? null : cursor.getString(offset + 79));
        entity.setFollowupFbg16(cursor.isNull(offset + 80) ? null : cursor.getDouble(offset + 80));
        entity.setFollowupOrgId16(cursor.isNull(offset + 81) ? null : cursor.getString(offset + 81));
        entity.setFollowupDate17(cursor.isNull(offset + 82) ? null : new java.util.Date(cursor.getLong(offset + 82)));
        entity.setFollowupWay17(cursor.isNull(offset + 83) ? null : cursor.getString(offset + 83));
        entity.setFollowupFbg17(cursor.isNull(offset + 84) ? null : cursor.getDouble(offset + 84));
        entity.setFollowupOrgId17(cursor.isNull(offset + 85) ? null : cursor.getString(offset + 85));
        entity.setFollowupDate18(cursor.isNull(offset + 86) ? null : new java.util.Date(cursor.getLong(offset + 86)));
        entity.setFollowupWay18(cursor.isNull(offset + 87) ? null : cursor.getString(offset + 87));
        entity.setFollowupFbg18(cursor.isNull(offset + 88) ? null : cursor.getDouble(offset + 88));
        entity.setFollowupOrgId18(cursor.isNull(offset + 89) ? null : cursor.getString(offset + 89));
        entity.setFollowupDate19(cursor.isNull(offset + 90) ? null : new java.util.Date(cursor.getLong(offset + 90)));
        entity.setFollowupWay19(cursor.isNull(offset + 91) ? null : cursor.getString(offset + 91));
        entity.setFollowupFbg19(cursor.isNull(offset + 92) ? null : cursor.getDouble(offset + 92));
        entity.setFollowupOrgId19(cursor.isNull(offset + 93) ? null : cursor.getString(offset + 93));
        entity.setFollowupDate20(cursor.isNull(offset + 94) ? null : new java.util.Date(cursor.getLong(offset + 94)));
        entity.setFollowupWay20(cursor.isNull(offset + 95) ? null : cursor.getString(offset + 95));
        entity.setFollowupFbg20(cursor.isNull(offset + 96) ? null : cursor.getDouble(offset + 96));
        entity.setFollowupOrgId20(cursor.isNull(offset + 97) ? null : cursor.getString(offset + 97));
        entity.setIsStandard(cursor.isNull(offset + 98) ? null : cursor.getString(offset + 98));
        entity.setHealthExamDate(cursor.isNull(offset + 99) ? null : new java.util.Date(cursor.getLong(offset + 99)));
        entity.setHealthExamEvaluate(cursor.isNull(offset + 100) ? null : cursor.getString(offset + 100));
        entity.setIsCancel(cursor.isNull(offset + 101) ? null : cursor.getInt(offset + 101));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(DiabetesLedger entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(DiabetesLedger entity) {
        return null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
