package net.greatsoft.main.db.helper;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import net.greatsoft.main.db.po.vaccine.VaccineBatchno;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VACCINE_BATCHNO".
*/
public class VaccineBatchnoDao extends AbstractDao<VaccineBatchno, Void> {

    public static final String TABLENAME = "VACCINE_BATCHNO";

    /**
     * Properties of entity VaccineBatchno.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property VaccineBatchnoId = new Property(0, String.class, "vaccineBatchnoId", false, "VACCINE_BATCHNO_ID");
        public final static Property MenufacturerId = new Property(1, String.class, "menufacturerId", false, "MENUFACTURER_ID");
        public final static Property BatchNumber = new Property(2, String.class, "batchNumber", false, "BATCH_NUMBER");
        public final static Property IsValid = new Property(3, Integer.class, "isValid", false, "IS_VALID");
        public final static Property Remark = new Property(4, String.class, "remark", false, "REMARK");
        public final static Property IsCancel = new Property(5, Integer.class, "isCancel", false, "IS_CANCEL");
        public final static Property CreateOrgId = new Property(6, String.class, "createOrgId", false, "CREATE_ORG_ID");
        public final static Property OrgName = new Property(7, String.class, "orgName", false, "ORG_NAME");
        public final static Property CreatorId = new Property(8, String.class, "creatorId", false, "CREATOR_ID");
        public final static Property Creator = new Property(9, String.class, "creator", false, "CREATOR");
        public final static Property CreateTime = new Property(10, java.util.Date.class, "createTime", false, "CREATE_TIME");
        public final static Property ModifiedOrgId = new Property(11, String.class, "modifiedOrgId", false, "MODIFIED_ORG_ID");
        public final static Property ModifiedOrgName = new Property(12, String.class, "modifiedOrgName", false, "MODIFIED_ORG_NAME");
        public final static Property ModifierId = new Property(13, String.class, "modifierId", false, "MODIFIER_ID");
        public final static Property Modifier = new Property(14, String.class, "modifier", false, "MODIFIER");
        public final static Property ModifiedTime = new Property(15, java.util.Date.class, "modifiedTime", false, "MODIFIED_TIME");
    };


    public VaccineBatchnoDao(DaoConfig config) {
        super(config);
    }
    
    public VaccineBatchnoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VACCINE_BATCHNO\" (" + //
                "\"VACCINE_BATCHNO_ID\" TEXT," + // 0: vaccineBatchnoId
                "\"MENUFACTURER_ID\" TEXT," + // 1: menufacturerId
                "\"BATCH_NUMBER\" TEXT," + // 2: batchNumber
                "\"IS_VALID\" INTEGER," + // 3: isValid
                "\"REMARK\" TEXT," + // 4: remark
                "\"IS_CANCEL\" INTEGER," + // 5: isCancel
                "\"CREATE_ORG_ID\" TEXT," + // 6: createOrgId
                "\"ORG_NAME\" TEXT," + // 7: orgName
                "\"CREATOR_ID\" TEXT," + // 8: creatorId
                "\"CREATOR\" TEXT," + // 9: creator
                "\"CREATE_TIME\" INTEGER," + // 10: createTime
                "\"MODIFIED_ORG_ID\" TEXT," + // 11: modifiedOrgId
                "\"MODIFIED_ORG_NAME\" TEXT," + // 12: modifiedOrgName
                "\"MODIFIER_ID\" TEXT," + // 13: modifierId
                "\"MODIFIER\" TEXT," + // 14: modifier
                "\"MODIFIED_TIME\" INTEGER);"); // 15: modifiedTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VACCINE_BATCHNO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VaccineBatchno entity) {
        stmt.clearBindings();
 
        String vaccineBatchnoId = entity.getVaccineBatchnoId();
        if (vaccineBatchnoId != null) {
            stmt.bindString(1, vaccineBatchnoId);
        }
 
        String menufacturerId = entity.getMenufacturerId();
        if (menufacturerId != null) {
            stmt.bindString(2, menufacturerId);
        }
 
        String batchNumber = entity.getBatchNumber();
        if (batchNumber != null) {
            stmt.bindString(3, batchNumber);
        }
 
        Integer isValid = entity.getIsValid();
        if (isValid != null) {
            stmt.bindLong(4, isValid);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(5, remark);
        }
 
        Integer isCancel = entity.getIsCancel();
        if (isCancel != null) {
            stmt.bindLong(6, isCancel);
        }
 
        String createOrgId = entity.getCreateOrgId();
        if (createOrgId != null) {
            stmt.bindString(7, createOrgId);
        }
 
        String orgName = entity.getOrgName();
        if (orgName != null) {
            stmt.bindString(8, orgName);
        }
 
        String creatorId = entity.getCreatorId();
        if (creatorId != null) {
            stmt.bindString(9, creatorId);
        }
 
        String creator = entity.getCreator();
        if (creator != null) {
            stmt.bindString(10, creator);
        }
 
        java.util.Date createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindLong(11, createTime.getTime());
        }
 
        String modifiedOrgId = entity.getModifiedOrgId();
        if (modifiedOrgId != null) {
            stmt.bindString(12, modifiedOrgId);
        }
 
        String modifiedOrgName = entity.getModifiedOrgName();
        if (modifiedOrgName != null) {
            stmt.bindString(13, modifiedOrgName);
        }
 
        String modifierId = entity.getModifierId();
        if (modifierId != null) {
            stmt.bindString(14, modifierId);
        }
 
        String modifier = entity.getModifier();
        if (modifier != null) {
            stmt.bindString(15, modifier);
        }
 
        java.util.Date modifiedTime = entity.getModifiedTime();
        if (modifiedTime != null) {
            stmt.bindLong(16, modifiedTime.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VaccineBatchno entity) {
        stmt.clearBindings();
 
        String vaccineBatchnoId = entity.getVaccineBatchnoId();
        if (vaccineBatchnoId != null) {
            stmt.bindString(1, vaccineBatchnoId);
        }
 
        String menufacturerId = entity.getMenufacturerId();
        if (menufacturerId != null) {
            stmt.bindString(2, menufacturerId);
        }
 
        String batchNumber = entity.getBatchNumber();
        if (batchNumber != null) {
            stmt.bindString(3, batchNumber);
        }
 
        Integer isValid = entity.getIsValid();
        if (isValid != null) {
            stmt.bindLong(4, isValid);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(5, remark);
        }
 
        Integer isCancel = entity.getIsCancel();
        if (isCancel != null) {
            stmt.bindLong(6, isCancel);
        }
 
        String createOrgId = entity.getCreateOrgId();
        if (createOrgId != null) {
            stmt.bindString(7, createOrgId);
        }
 
        String orgName = entity.getOrgName();
        if (orgName != null) {
            stmt.bindString(8, orgName);
        }
 
        String creatorId = entity.getCreatorId();
        if (creatorId != null) {
            stmt.bindString(9, creatorId);
        }
 
        String creator = entity.getCreator();
        if (creator != null) {
            stmt.bindString(10, creator);
        }
 
        java.util.Date createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindLong(11, createTime.getTime());
        }
 
        String modifiedOrgId = entity.getModifiedOrgId();
        if (modifiedOrgId != null) {
            stmt.bindString(12, modifiedOrgId);
        }
 
        String modifiedOrgName = entity.getModifiedOrgName();
        if (modifiedOrgName != null) {
            stmt.bindString(13, modifiedOrgName);
        }
 
        String modifierId = entity.getModifierId();
        if (modifierId != null) {
            stmt.bindString(14, modifierId);
        }
 
        String modifier = entity.getModifier();
        if (modifier != null) {
            stmt.bindString(15, modifier);
        }
 
        java.util.Date modifiedTime = entity.getModifiedTime();
        if (modifiedTime != null) {
            stmt.bindLong(16, modifiedTime.getTime());
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public VaccineBatchno readEntity(Cursor cursor, int offset) {
        VaccineBatchno entity = new VaccineBatchno( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // vaccineBatchnoId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // menufacturerId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // batchNumber
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // isValid
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // remark
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // isCancel
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // createOrgId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // orgName
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // creatorId
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // creator
            cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)), // createTime
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // modifiedOrgId
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // modifiedOrgName
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // modifierId
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // modifier
            cursor.isNull(offset + 15) ? null : new java.util.Date(cursor.getLong(offset + 15)) // modifiedTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VaccineBatchno entity, int offset) {
        entity.setVaccineBatchnoId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setMenufacturerId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBatchNumber(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIsValid(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setRemark(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setIsCancel(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setCreateOrgId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setOrgName(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCreatorId(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setCreator(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setCreateTime(cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)));
        entity.setModifiedOrgId(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setModifiedOrgName(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setModifierId(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setModifier(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setModifiedTime(cursor.isNull(offset + 15) ? null : new java.util.Date(cursor.getLong(offset + 15)));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(VaccineBatchno entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(VaccineBatchno entity) {
        return null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
